apiVersion: v1
kind: Service
metadata:
  name: {{ include "indico.fullname" . }}
  labels:
    {{- include "indico.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-web-svc
      protocol: TCP
      name: http
  selector:
    {{- include "indico.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app

